.\" Copyright (c) 1997, Apple Computer, Inc.  All rights reserved.
.\"
.Dd August 13, 1997
.Dt VM_STAT 1
.Os "Mac OS X"
.Sh NAME
.Nm vm_stoop
.Nd show Mach virtual memory statistics without making you feel dumb
.Sh SYNOPSIS
.Nm vm_stoop
.Ar modeline
.Sh DESCRIPTION
.Nm vm_stoop
displays Mach virtual memory statistics. The same statistics are 
available via the
.Nm vm_stat
tool but when using
.Nm vm_stoop(id)
 they are formatted in units of bytes rather than Pages
so that they may be more easily understoop by (vm_)stoopid humans.

The values to be reported must be chosen using a
.NM modeline
argument, where each character in the modeline requests a statistic from
the following list to be displayed.
.Bl -tag -width indent
.It f
Memory free
.It a
Memory active
.It i
Memory inactive
.It ~
Memory speculative
.It t
Memory throttled
.It w
Memory wired down
.It u
Memory purgeable
.It c
Memory copy-on-write
.It 0
Memory zero filled
.It r
Memory reactivated
.It U
Memory purged
.It b
File-backed memory
.It ?
Anonymous memory
.It .
Memory stored in compressor
.It o
Memory occupied by compressor
.El
.Sh EXAMPLES
The following examples are shown as given to the shell:
.Pp
Report free memory
.Pp
.D1 Li "vm_stoop f"
.Pp
Report free and active memory
.Pp
.D1 Li "vm_stoop fa"
.Pp
.Pp
